### ISSUE TITLE
[THEMES] Create New Themes

### ISSUE THREAD

**Issue by gbcode98** [WizardCodeForge/pokemon-status#1]
Develop new themes for users.

**Comment by gbcode98** [comment]
- **DITTO THEME** 

![image](https://github.com/user-attachments/assets/2f2374bf-bd41-4a45-939a-563034b8c80b)
![image](https://github.com/user-attachments/assets/2244e20c-2aab-4faf-bfc8-2aff2be3a285)



- **SYLVEON THEME** 

![image](https://github.com/user-attachments/assets/c3ea3139-902c-466f-a385-40ee87e405e0)
![image](https://github.com/user-attachments/assets/9cbe5ed2-4c46-4cb0-9fcd-8c740ae0d236)


- **GLACEON THEME** 

![image](https://github.com/user-attachments/assets/48293d68-6774-4ad1-bdbc-34871341ef63)
![image](https://github.com/user-attachments/assets/e1528421-4be0-4154-8581-81ce1920f081)

- **MARSHADOW THEME** 

![image](https://github.com/user-attachments/assets/25d49cd8-4c12-4c63-a3f8-549d934aeae3)
![image](https://github.com/user-attachments/assets/43bb4412-4eb9-49e6-825c-e097450b7b86)

**Comment by CriticalNoob02** [comment]
Feito, ja vou adicionar na doc
